# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sc2_achievements"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eduardo Grajeda Blandon"]
  s.date = "2012-09-21"
  s.description = "This library downloads all the achievements from a Starcraft II player's public profile and package them as an array."
  s.email = "tatofoo@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/sc2_achievements.rb",
    "lib/sc2_achievements/category_page.rb",
    "lib/sc2_achievements/homepage.rb",
    "lib/sc2_achievements/page.rb",
    "sc2_achievements.gemspec",
    "spec/cassettes/achievements-homepage-and-first-categories.yml",
    "spec/cassettes/achievements-homepage-and-guide-three.yml",
    "spec/cassettes/achievements-homepage.yml",
    "spec/cassettes/all-achievements.yml",
    "spec/cassettes/all-selected-achievements.yml",
    "spec/cassettes/homepage-and-recent-achievements-category-pages.yml",
    "spec/cassettes/mar-sara-missions.yml",
    "spec/cassettes/solo-league.yml",
    "spec/sc2_achievements/category_page_spec.rb",
    "spec/sc2_achievements/homepage_spec.rb",
    "spec/sc2_achievements/page_spec.rb",
    "spec/sc2_achievements_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/egrajeda/sc2_achievements"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Download all the achievements of a SC2 player."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<vcr>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<vcr>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<vcr>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

